name: Python ML application

on: 
  push:

jobs:

  run_preprocessing_and_ml:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'

      - name: Install Jupyter
        run: |
          pip install jupyter

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt  # install your Python dependencies

      - name: Run Jupyter Notebook
        run: |
          jupyter nbconvert --to script preprocessing_titanic.ipynb  # Replace 'your_notebook.ipynb' with your notebook filename
          python preprocessing_titanic.py  # Execute the generated Python script

      - name: Add Changes
        run: |
          git config --local user.email "narenmouria.g@gmail.com"
          git config --local user.name "narenmouria.g"
          git add output.xlsx
          git commit -m "Add processed Excel file"
          git push -u origin test

      - name: Run ML Program
        run: python titanic.py  # Replace 'your_ml_program.py' with your ML program filename
