name: On Push Run

on: push

env:
  DEVOPS_DIR: new-repo

jobs:
  hello-world:
    name: Hello world
    runs-on: ubuntu-latest
    steps:
    - name: Check-out devops repository
      uses: actions/checkout@v3
      with:
        repository: naren-3103/new-repo
        token: ${{ secrets.GITHUB_TOKEN }}
        path: ${{ env.DEVOPS_DIR }}

    - name: Hello World
      run: python ${{ env.DEVOPS_DIR }}/hello.py
      shell: sh
